spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
        schema.registry.url: http://localhost:8085
  application:
    name: spring-kafka-demo

kafka:
  topic: topic1

logging:
  level:
    se.ohou: debug

