spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    properties:
        schema.registry.url: http://localhost:8085
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  application:
    name: spring-kafka-demo

kafka:
  topic: topic1

logging:
  level:
    se.ohou: debug
